### ISSUE TITLE
Timeouts should generate UNKNOWN, not WARN

### ISSUE THREAD

**Issue by troelsarvin** [dangmocrang/check_idrac#3]
Compared generation 1, I get a lot of SNMP timeout situations when I ask the script to check all hardware (i.e. when I do not provide a -w option). I'm not sure why that is, but I've returned to generation 1 for the time being.

By the way, when the timeouts occur, v. 2.0b6 yields a WARNING (code 1). I believe this is not how it's supposed to be: I believe that it should yield an UNKNOWN (code 3) state. So I suggest adjusting line 439 so that
  sys.exit(1)
is changed to
  sys.exit(3)

**Comment by dangmocrang** [comment]
Hi Arvin,

V2 got more time out cause in v1 I query all information at once then process them, in v2 I for each type of hardware I call only their table of info, so it turns into multiple query SNMP and idrac was bad at handle multi requests.
My team have worked with dell to upgrade new firmware and the problem fixed.

That why I return code 1 because sometime idrac will hang up while handling snmp.

Regards,
Dung Nguyen

-----Original Message-----
